# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chickenhealth

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chickenhealth.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0948a3039dcf45859e12306b0b75121b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4be77c45d2d841109cc55c3b0a846e7f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chickenhealth.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0948a3039dcf45859e12306b0b75121b }}/chicken:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chickenhealth'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bc87a73f2e55478e9e2e523bf31821f0 }}
        images: 'chickenhealth.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0948a3039dcf45859e12306b0b75121b }}/chicken:${{ github.sha }}'